server:
  port: 8080
  address: 0.0.0.0  # ← 모든 네트워크 인터페이스에서 접근 허용 (localhost 외부 접근 가능)

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver # MySQL 드라이버
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 8       # 서버 처리 직원 숫자
      minimum-idle: 8             # 기다리는 사람 숫자
      max-lifetime: 1800000 
      connection-timeout: 30000  # 꽉찼을때 사람들 기다리는 시간
  data:
    redis:
      host: ${REDIS_HOST:localhost} # 없으면 localhost 사용
      port: ${REDIS_PORT:6379}

  jpa:
    show-sql: true # sql 로그 확인
    hibernate:
      ddl-auto: none # 업데이트나 생성 방지  
    properties:
      hibernate:
        format_sql: true #sql 들여쓰기 트루해 놓는게 정신건강에 좋음

  servlet:
    multipart:
      max-file-size: 20MB      # 파일 하나당 최대 크기 (기본 1MB -> 20MB로 증량)
      max-request-size: 20MB
      
jwt:
  secret: ${JWT_SECRET_KEY} 
  access-token-valid-in-seconds: 3600
  refresh-token-valid-in-seconds: 604800


cloud:
  aws:
    s3:
      bucket: bomming-media  # 본인 버킷 이름
    credentials:
      access-key: ${AWS_ACCESS_KEY}  # .env
      secret-key: ${AWS_SECRET_KEY}  # .env
    region:
      static: ap-northeast-2 # 서울 (버지니아면 us-east-1)
    stack:
      auto: false
